# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c4df861cc18bf21e3f16ec4aeba5406680d7824673f4073b0d41219395fcfb73db821d656231f650382b728c5142bec7b9554178f7e39c278fb73e0bd03a6d8

test:
  secret_key_base: 574171456c78898d0d23efab8acbf93a2413fd976c1076e3662ea89b71452c1e5bc55d9b32baea9002b049fa68636ec49bf985933c84896b36f4efe6ad363500

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
